const products = [
    {
        id: "1",
        artistName: "Common",
        albumName: "Be",
        releaseDate: 2005,
        producers: "Kanye West, J Dilla",
        albumCover: "images/BE.jpg",
        genres: `Hip hop`,
        description: `
      Be é o sexto álbum de estúdio do rapper americano Common. Foi lançado em 24 de maio de 2005.
      O álbum foi produzido principalmente pelo rapper e produtor Kanye West.
      Be também foi um sucesso de crítica, recebendo aclamação e elogios de vários críticos e publicações musicais.`,
        price: 0.0,
        numInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    {
        id: "2",
        artistName: "Bob Dylan",
        albumName: "Nashville Skyline",
        releaseDate: 1969,
        producers: "pd",
        albumCover: "images/NASHVILLESKYLINE.jpg",
        description: `Lorem rizzle dolizzle sit amizzle, daahng dawg adipiscing i saw beyonces tizzles and my pizzle went crizzle. Nullizzle sapien velit, bow wow wow volutpizzle, suscipit quis, gravida vel, fo shizzle. `,
        genres: `Country`,
        price: 0.0,
        numInStock: 0,
        rating: 4.5,
        numReviews: 12,
    },
    {
        id: "3",
        artistName: "Raekwon",
        albumName: "Only Built 4 Cuban Linx...",
        releaseDate: 1995,
        producers: "pd",
        albumCover: "images/OBFCL.jpg",
        description: "",
        genres: `Hip hop`,
        price: 0.0,
        numInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    {
        id: "4",
        artistName: "Prince",
        albumName: "1999",
        releaseDate: 1996,
        producers: "pd",
        albumCover: "images/1999.jpg",
        description: "",
        genres: `Hip hop`,
        price: 0.0,
        numInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    {
        id: "5",
        artistName: "Gonzaguinha",
        albumName: "Recado",
        releaseDate: 1978,
        producers: "pd",
        albumCover: "images/RECADO.jpg",
        description: "",
        genres: `Hip hop`,
        price: 0.0,
        numInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    {
        id: "6",
        artistName: "Thelonious Monk",
        albumName: "Misterioso",
        releaseDate: 1958,
        producers: "pd",
        albumCover: "images/MISTERIOSO.jpg",
        description: "",
        genres: `Hip hop`,
        price: 0.0,
        numInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    {
        id: "7",
        artistName: "Miles Davis",
        albumName: "Sketches of Spain",
        releaseDate: 1960,
        producers: "pd",
        albumCover: "images/SKETCHES.jpg",
        description: "",
        genres: `Hip hop`,
        price: 0.0,
        numInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    {
        id: "8",
        artistName: "Wyclef Jean",
        albumName: "The Carnival",
        releaseDate: 1995,
        producers: "pd",
        albumCover: "images/CARNIVAL.jpg",
        description: "",
        genres: `Hip hop`,
        price: 0.0,
        numInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    {
        id: "9",
        artistName: "Jay-Z",
        albumName: "Reasonable Doubt",
        releaseDate: 1996,
        producers: "pd",
        albumCover: "images/REASONABLE.jpg",
        description: "Its fo rizzle nizzle mi fo maurizzle stuff bibendum. ",
        genres: `Hip hop`,
        price: 0.0,
        numInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
];

export default products;
