const products = [
    {
        artistName: "Common",
        albumName: "Be",
        releaseDate: 2005,
        producers: "Kanye West, J Dilla",
        albumCover: "images/BE.jpg",
        genres: `Hip hop`,
        description: `
      Be é o sexto álbum de estúdio do rapper americano Common. Foi lançado em 24 de maio de 2005.
      O álbum foi produzido principalmente pelo rapper e produtor Kanye West.
      Be também foi um sucesso de crítica, recebendo aclamação e elogios de vários críticos e publicações musicais.`,
        price: 0.0,
        numInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    {
        artistName: "Bob Dylan - Nashville Skyline",
        albumName: "Be",
        releaseDate: 1969,
        producers: "pd",
        albumCover: "images/NASHVILLE_SKYLINE.jpg",
        description: `Lorem rizzle dolizzle sit amizzle, daahng dawg adipiscing i saw beyonces tizzles and my pizzle went crizzle. Nullizzle sapien velit, bow wow wow volutpizzle, suscipit quis, gravida vel, fo shizzle. `,
        genres: `Country`,
        price: 0.0,
        numInStock: 0,
        rating: 4.5,
        numReviews: 12,
    },
    {
        artistName: "Raekwon - Only Built 4 Cuban Linx...",
        albumName: "Be",
        releaseDate: 1995,
        producers: "pd",
        albumCover: "images/OBFCL.jpg",
        description: "",
        genres: `Hip hop`,
        price: 0.0,
        numInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    {
        artistName: "Prince - 1999",
        albumName: "Be",
        releaseDate: 1996,
        producers: "pd",
        albumCover: "images/1999.jpg",
        description: "",
        genres: `Hip hop`,
        price: 0.0,
        numInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    {
        artistName: "Gonzaguinha - Recado",
        albumName: "Be",
        releaseDate: 1978,
        producers: "pd",
        albumCover: "images/RECADO.jpg",
        description: "",
        genres: `Hip hop`,
        price: 0.0,
        numInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    {
        artistName: "Thelonious Monk - Misterioso",
        albumName: "Be",
        releaseDate: 1958,
        producers: "pd",
        albumCover: "images/MISTERIOSO.jpg",
        description: "",
        genres: `Hip hop`,
        price: 0.0,
        numInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    {
        artistName: "Miles Davis - Sketches of Spain",
        albumName: "Be",
        releaseDate: 1960,
        producers: "pd",
        albumCover: "images/SKETCHES.jpg",
        description: "",
        genres: `Hip hop`,
        price: 0.0,
        numInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    {
        artistName: "Wyclef Jean - The Carnival",
        albumName: "Be",
        releaseDate: 1995,
        producers: "pd",
        albumCover: "images/CARNIVAL.jpg",
        description: "",
        genres: `Hip hop`,
        price: 0.0,
        numInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    {
        artistName: "Jay-Z - Reasonable Doubt",
        albumName: "Be",
        releaseDate: 1996,
        producers: "pd",
        albumCover: "images/REASONABLE.jpg",
        description: "Its fo rizzle nizzle mi fo maurizzle stuff bibendum. ",
        genres: `Hip hop`,
        price: 0.0,
        numInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
];

export default products;
